"""
minjiezhang123@gmail.com    Mar,18,2020
python3

1, gaytypes.py in CRSSANT will generate 5 different types of sam files:
   cont.sam;  gap1.sam;  gapm.sam;  trans/rri.sam;  homo.sam;  bad.sam
2, gap1filter.sam and trans/rri.sam are combined to produce alignfile sam and
   used to assemble alignments to DGs and NGs using the crssant.py script.
3, However, gap1filter.sam contains some chimeric reads with "SA" tag, which
   generated by two distant chimeric alignments. The "SA" tag in gap1filter.sam
   will trigger error when performing CRSSANT analysis (Line 163).
4, This script can be used to merger gap1filter.sam and trans/rri.sam to one sam
   file and remove "SA" tag of the reads in gap1filter.sam.

Usage:
   python merger.py gap1filter.sam trans/rri.sam outprefix
"""


#1. input and output setup
################################################################################
from datetime import datetime
def timenow(): return str(datetime.now())[:-7]
import sys
if len(sys.argv) < 2:
    print("Usage: python merger.py  gap1filter.sam trans.sam  outprefix")
    print("gap1filter.sam:  filtered two-segment gapped alignments.")
    print("trans/rri.sam:   different str/chr chimeric alignments.")
    sys.exit()
gap1sam = open(sys.argv[1],"r")    
rrisam = open(sys.argv[2],"r")
outsam = open(sys.argv[3]+'_crssant.sam',"w")


#2. Processing the sam file
################################################################################
print(timenow()+" Started merger.py ...")
print(timenow()+" Processing gap1filter.sam ...")
header='';
for line in gap1sam: 
    if line[0]=="@": outsam.write(line)
    else:
        if "SA:Z:" not in line.split()[-1]: outsam.write(line)
        if "SA:Z:" in line.split()[-1]: outsam.write('\t'.join(line.split()[:-2])+'\n')

print(timenow()+" Processing trans/rri.sam ...")
for line in rrisam: 
    if line[0]!="@": outsam.write(line)

gap1sam.close()
rrisam.close()
outsam.close()
